spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      enabled: true # console enabled
      path: /h2-console  # rootPath:port/h2-console (ex : localhost:8080/h2-console)
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 # TODO : remove and fetchJoin || ~

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password: